name: Generate and Deploy AI Content to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      prompt:
        description: 'Custom prompt for content generation'
        required: false
        default: 'Generate an engaging HTML page about the latest in technology'
      page_title:
        description: 'Title for the generated page'
        required: false
        default: 'AI Generated Content'
      ai_provider:
        description: 'AI provider to use (anthropic or openai)'
        required: false
        default: 'anthropic'
        type: choice
        options:
          - anthropic
          - openai
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday at midnight

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate-content:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.pages.outputs.artifact-name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate HTML content with AI
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AI_PROVIDER: ${{ github.event.inputs.ai_provider || 'anthropic' }}
          PROMPT: ${{ github.event.inputs.prompt || 'Generate an engaging HTML page about the latest in technology' }}
          PAGE_TITLE: ${{ github.event.inputs.page_title || 'AI Generated Content' }}
        run: |
          python scripts/generate_content.py

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: generate-content
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4